name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'   # кэш зависимостей
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm eslint . --max-warnings=0
      - run: pnpm tsc -b --noEmit
      # build можно включить позже, когда добавите секреты БД:
      # - run: pnpm build
      #   env:
      #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
      #     PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}